vector_test :: () {

    // Vec2
    operator_test("_Vec2d", "+");
    operator_test("_Vec2d", "-");
    operator_test("_Vec2d", "*");
    operator_test("_Vec2d", "/");

    operator_test("_Vec2", "+");
    operator_test("_Vec2", "-");
    operator_test("_Vec2", "*");
    operator_test("_Vec2", "/");

    operator_test("_Point2", "+");
    operator_test("_Point2", "-");
    operator_test("_Point2", "*");
    operator_test("_Point2", "/");

    operator_test("_Point2d", "+");
    operator_test("_Point2d", "-");
    operator_test("_Point2d", "*");
    operator_test("_Point2d", "/");

    // Vec3
    operator_test("_Vec3d", "+");
    operator_test("_Vec3d", "-");
    operator_test("_Vec3d", "*");
    operator_test("_Vec3d", "/");

    operator_test("_Vec3", "+");
    operator_test("_Vec3", "-");
    operator_test("_Vec3", "*");
    operator_test("_Vec3", "/");

    operator_test("_Point3", "+");
    operator_test("_Point3", "-");
    operator_test("_Point3", "*");
    operator_test("_Point3", "/");

    operator_test("_Point3d", "+");
    operator_test("_Point3d", "-");
    operator_test("_Point3d", "*");
    operator_test("_Point3d", "/");

    // Vec4
    operator_test("_Vec4d", "+");
    operator_test("_Vec4d", "-");
    operator_test("_Vec4d", "*");
    operator_test("_Vec4d", "/");

    operator_test("_Vec4", "+");
    operator_test("_Vec4", "-");
    operator_test("_Vec4", "*");
    operator_test("_Vec4", "/");

    operator_test("_Point4", "+");
    operator_test("_Point4", "-");
    operator_test("_Point4", "*");
    operator_test("_Point4", "/");

    operator_test("_Point4d", "+");
    operator_test("_Point4d", "-");
    operator_test("_Point4d", "*");
    operator_test("_Point4d", "/");
}

